### ISSUE TITLE
data download

### ISSUE THREAD

**Issue by husthuke** [thunlp/WantWords#1]
The data download address may be wrong and the data cannot be downloaded.(https://cloud.tsinghua.edu.cn/...)

**Comment by syheliel** [comment]
I have tried to download data from `README.md` and it worked.

**Comment by kimhung-uit** [comment]
Hi syheliel,
First of all, your project is amazing, but downloaded data from the given link in README.md is insufficient to run the project (e.g., missing 'wordTrans_Ch_En_Sort.json', 'wordTrans_En_Ch_Sort.json', 'word2synset_synset.txt', etc.).
It would be great if you can provide the link with such missing files. 

Thank you so much.

**Comment by huangxinping** [comment]
@syheliel 
The data can not be downloaded from README.md or README_ZH.md as well. 
Could you send me the files?

Thank you so much.

**Comment by syheliel** [comment]
The data in `https://cloud.tsinghua.edu.cn/f/db14bbfb78e0452bb2f1/` seems to be invalid 😢 . @Fanchao-Qi Would you like to fix the link?

**Comment by Fanchao-Qi** [comment]
Hi, we are sorry that some of the shared data might have the risk of infringing copyright. Therefore, we cancel the data downloading for now. We will check and update the data ASAP.

**Comment by Fanchao-Qi** [comment]
The download link of data and pre-trained models has been resumed.

**Comment by anantshahi** [comment]
Hi, first of all this is an amazing project. But, there are a few files missing from the download link. For example : website_RDwd_def_for_website_En.json

Can you please help me out on this or maybe provide a link to it as well. Thanks a lot in advance
