### ISSUE TITLE
something funny

### ISSUE THREAD

**Issue by w570955342** [thunlp/WantWords#10]
![de6f3279e94e6692ec5e666c3aeed8f](https://user-images.githubusercontent.com/42182202/144437677-5105d33d-24f2-4a06-b8e4-813449ebcdcc.png)

I firmly believe it will get better.

**Comment by Fanchao-Qi** [comment]
There are always 100 words listed. The most related words are ranked in front with background color, while the other words may not be related. Please give feedback to improve the model by clicking 👍 or 👎 in the floating window of each word.
