### ISSUE TITLE
Missing data file from given link in README.md

### ISSUE THREAD

**Issue by kimhung-uit** [thunlp/WantWords#2]
Hi syheliel,
First of all, your project is amazing, but downloaded data from the given link in README.md is insufficient to run the project (e.g., missing 'wordTrans_Ch_En_Sort.json', 'wordTrans_En_Ch_Sort.json', 'word2synset_synset.txt', etc.).
It would be great if you can provide the link with such missing files.

Thank you so much.

**Comment by Fanchao-Qi** [comment]
We have uploaded the [new data](https://cloud.tsinghua.edu.cn/d/811dcb428ed24480bc60/), please check whether the problem still exists. Feel free to reopen this issue.
