### ISSUE TITLE
做了个简易版的小程序，欢迎体验

### ISSUE THREAD

**Issue by Q3B0** [thunlp/WantWords#25]
![微信图片_20211221113920](https://user-images.githubusercontent.com/8241503/146867036-300df509-4564-4b55-8dea-16d7cba9cbee.jpg)

**Comment by hukz37** [comment]
你这是抓包接口搞的吗😁

**Comment by Q3B0** [comment]
> 你这是抓包接口搞的吗😁

直接请求的接口

**Comment by Fanchao-Qi** [comment]
我们的小程序已经在开发中，预计月底前可以上线。

**Comment by Fanchao-Qi** [comment]
@Q3B0 你好，我们开发的小程序已经正式上线（具有更丰富的功能），为了避免用户混淆，还请将你开发的简易版下线，谢谢！ 也欢迎联系我（微信 fanchao_qi）提出你对现有版本的意见和建议😃

![gh_cea511adb2d2_860](https://user-images.githubusercontent.com/12222818/154277002-9534bc1e-19d9-49da-b174-f8b7da00141f.jpg)
