### ISSUE TITLE
英-汉中搜索 “google” 出现页面错误，可重现。

### ISSUE THREAD

**Issue by scavin** [thunlp/WantWords#3]
@liu 同学的反馈：  https://meta.appinn.net/t/topic/27375/

![5271c90a70562a624f63a104c33c07fd12210ce6](https://user-images.githubusercontent.com/716584/140703683-4d0d3e92-8928-4ef4-b5d0-47d11f03b2f2.png)

**Comment by Fanchao-Qi** [comment]
感谢反馈！我们会尽快修复！

**Comment by Fanchao-Qi** [comment]
已修复。
