### ISSUE TITLE
嗯……我怀疑不少网络风月文学作品入驻了训练库，而且量还很大。

### ISSUE THREAD

**Issue by macheteluc** [thunlp/WantWords#30]
![image](https://user-images.githubusercontent.com/29720234/148344076-ecd8b531-a142-4373-ae6b-c76c042384d3.png)

**Comment by Monica-Han** [comment]
哈哈哈哈哈哈笑死

**Comment by Fanchao-Qi** [comment]
我们已注意到这个问题并且在着手解决😅

**Comment by Guiquan-27** [comment]
哈哈，这个要解决的，有时候确实并不是自己想要的意思

**Comment by Fanchao-Qi** [comment]
更换新模型后，该问题已经解决。
