### ISSUE TITLE
请问在哪可以找到wd_def_for_website_xhzd+ch+xh.json

### ISSUE THREAD

**Issue by wynshiter** [thunlp/WantWords#31]
请问从这句代码中要加载的文件，在哪里找？
wd_data_ = json.load(open(BASE_DIR + 'wd_def_for_website_xhzd+ch+xh.json',encoding='utf-8'))

**Comment by Fanchao-Qi** [comment]
请问已经从清华云盘下载最新的数据和模型文件了么？

**Comment by Fanchao-Qi** [comment]
已修复

**Comment by AMchuAMchuAMchu** [comment]
邮件已收到！谢谢！
