### ISSUE TITLE
汉-英页面是改版了吗

### ISSUE THREAD

**Issue by pocketdr** [thunlp/WantWords#36]
![image](https://user-images.githubusercontent.com/45301505/164356128-8bc2024a-639c-4ebb-842e-842860aaaf36.png)

之前的筛选不见了

**Comment by AMchuAMchuAMchu** [comment]
邮件已收到！谢谢！

**Comment by thezbm** [comment]
![image](https://user-images.githubusercontent.com/24851999/164360922-d0ee9b04-b9bd-4a38-bdf6-4e1e0d3f6c1a.png)
English页面也是如此。

**Comment by Fanchao-Qi** [comment]
服务器故障，已解决。
