### ISSUE TITLE
三本人民向世一大发来贺电

### ISSUE THREAD

**Issue by Everloom-129** [thunlp/WantWords#4]
很有趣的项目
以及为什么三本的搜索结果这么奇怪[AC01]
![image](https://user-images.githubusercontent.com/72364066/140913872-941935b8-c628-4507-9137-6ff4285664aa.png)

**Comment by Fanchao-Qi** [comment]
谢谢鼓励！
因为目前模型是用词典定义数据训练的，所以如果词典定义中没有出现“浙江大学”这样的词语，模型可能会根据输入文本中某些特定的词语（比如浙江、大学）来去找相关词。
随着反馈的人数越来越多，模型会做的更精准哈。
