### ISSUE TITLE
我能否使用Web API，为WantWords开发APP，并发布到Google Play和App Store?

### ISSUE THREAD

**Issue by droplet-js** [thunlp/WantWords#40]
如题，我觉得WantWords是一个非常好用的工具，但是没有APP支持，在日常使用中还是有点麻烦。故而，想用WantWords的Web API开发APP

**Comment by AMchuAMchuAMchu** [comment]
邮件已收到！谢谢！

**Comment by Fanchao-Qi** [comment]
你好，目前WantWords已经有小程序，同时APP正在开发中哈。

另外API后期也会同步开放的，但是预期会通过RESTful API的方式提供。

**Comment by droplet-js** [comment]
@Fanchao-Qi -.-!!! ... 额 ... 这个，你们的开发速度有点慢 ...

**Comment by yueqing-wolai** [comment]
API 开发进度怎么样么
