### ISSUE TITLE
__Originally posted by @Yynny in https://github.com/camsong/You-Dont-Need-jQuery/issues/254__

### ISSUE THREAD

**Issue by Yynny** [thunlp/WantWords#41]
__Originally posted by @Yynny in https://github.com/camsong/You-Dont-Need-jQuery/issues/254__

__Originally posted by @Yynny in https://github.com/NabilAFK/nabilafk.github.io/issues/3__

**Comment by AMchuAMchuAMchu** [comment]
邮件已收到！谢谢！

**Comment by Yynny** [comment]
- [ ] I [[]()]()
