### ISSUE TITLE
提供的下载链接已无法下载

### ISSUE THREAD

**Issue by liwenju0** [thunlp/WantWords#43]
在清华大学云盘下载模型文件时，显示 size too large。
哪位有模型文件，希望热心分享一下。谢谢

**Comment by Fanchao-Qi** [comment]
百度网盘：
链接: https://pan.baidu.com/s/1glK50AKo0EinyzRMe5taXA?pwd=hvbj 提取码: hvbj

**Comment by liwenju0** [comment]
谢谢！
